# Generated by Django 3.2.12 on 2022-05-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
