# Generated by Django 3.2.12 on 2022-05-03 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220503_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='productname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.item'),
        ),
    ]
