# Generated by Django 3.2.12 on 2022-05-03 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productselling', '0002_product_avalable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shopname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
