# Generated by Django 3.2.12 on 2022-05-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productselling', '0003_customer_shopname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productselling.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productselling.product')),
            ],
        ),
    ]
