# Generated by Django 3.2.12 on 2022-05-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productselling', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
