# Generated by Django 3.2.12 on 2022-05-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productselling', '0006_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalable',
            new_name='avaliable',
        ),
    ]
