# Generated by Django 3.2.12 on 2022-05-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productselling', '0007_rename_avalable_product_avaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
