# Generated by Django 3.2.12 on 2022-05-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productselling', '0008_order_gst_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='gst_price',
            new_name='gst',
        ),
    ]
